#!/bin/bash

# WM Independent Hotkeys

# Terminal Emulator
super + Return
    kitty

# Program Launcher
super
    exec rofi -modi drun -show

# Program Search
super + m
    bash "${HOME}/.scripts/search"

# Program Theme
super + z
    bash "${HOME}/.scripts/theme"

# Program Screenshots
super + s
    bash "${HOME}/.scripts/screenshots"

# Program Powermenu
super + x
    bash "${HOME}/.scripts/powermenu"

# Program Network
super + n
    bash "${HOME}/.scripts/network"

# Program Compositor
super + c
    bash "${HOME}/.scripts/comp"

# Program Border
super + b
    bash "${HOME}/.scripts/border"

# Reload sxhkd Configuration
super + Escape
    pkill -USR1 -x sxhkd

# BSPWM Hotkeys

# Quit/Restart BSPWM
super + alt + {q,r}
    bspc {quit,wm -r}

# Close and Kill
super + {_,shift + }w
    bspc node -{c,k}

# Toggle Tiled and Monocle Layout
super + m
    bspc desktop -l next

# Swap Marked Node with Preselected Node
super + y
    bspc node newest.marked.local -n newest.!automatic.local

# Swap Current Node with Biggest Window
super + g
    bspc node -s biggest.window

# State/Flags

# Set Window State
super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# Set Node Flags
super + ctrl + {m,x,y,z}
    bspc node -g {marked,locked,sticky,private}

# Focus/Swap

# Focus Node in Given Direction
super + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

# Focus Node for Path Jump
super + {p,b,comma,period}
    bspc node -f @{parent,brother,first,second}

# Focus Next/Previous Window in Current Desktop
super + {_,shift + }c
    bspc node -f {next,prev}.local.!hidden.window

# Focus Next/Previous Desktop in Current Monitor
super + bracket{left,right}
    bspc desktop -f {prev,next}.local

# Focus Last Node/Desktop
super + {grave,Tab}
    bspc {node,desktop} -f last

# Focus Older or Newer Node in Focus History
super + {o,i}
    bspc wm -h off; \
    bspc node {older,newer} -f; \
    bspc wm -h on

# Focus or Send to Given Desktop
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'

# Preselect

# Preselect Direction
super + ctrl + {h,j,k,l}
    bspc node -p {west,south,north,east}

# Preselect Ratio
super + ctrl + {1-9}
    bspc node -o 0.{1-9}

# Cancel Preselection for Focused Node
super + ctrl + space
    bspc node -p cancel

# Cancel Preselection for Focused Desktop
super + ctrl + shift + space
    bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

# Move/Resize

# Expand a Window by Moving a Side Outward
super + alt + {h,j,k,l}
    bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# Contract a Window by Moving a Side Inward
super + alt + shift + {h,j,k,l}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# Move a Floating Window
super + {Left,Down,Up,Right}
    bspc node -v {-20 0,0 20,0 -20,20 0}

# Brightness

# Brightness Up
XF86MonBrightnessUp
    xbacklight -inc 1; \
    dunstify "盛 Brightness Up:" -h int:value:$(xbacklight -get | cut -f 1 -d '.') -t 1000 -r 1

# Brightness Down
XF86MonBrightnessDown
    xbacklight -dec 1; \
    dunstify "滛 Brightness Down:" -h int:value:$(xbacklight -get | cut -f 1 -d '.') -t 1000 -r 1

# Pipewire Controls Speaker Volume

# Volume Up
XF86AudioRaiseVolume
    pactl set-sink-volume @DEFAULT_SINK@ +1%; \
    dunstify " Increase Volume:" -h int:value:$(pactl list sinks | grep 'Volume:' | head -n 1 | awk -F / '{print $2}' | sed 's/ %//') -t 1000 -r 1

# Volume Down
XF86AudioLowerVolume
    pactl set-sink-volume @DEFAULT_SINK@ -1%; \
    dunstify "奔 Decrease Volume:" -h int:value:$(pactl list sinks | grep 'Volume:' | head -n 1 | awk -F / '{print $2}' | sed 's/ %//') -t 1000 -r 1

# Pipewire Controls Mic Volume

# Mic Volume Up
shift + XF86AudioRaiseVolume
    pactl set-source-volume @DEFAULT_SOURCE@ +1%; \
    dunstify " Mic Volume Up:" -h int:value:$(pactl list sources | grep 'Volume:' | head -n 1 | awk -F / '{print $2}' | sed 's/ %//') -t 1000 -r 1

# Mic Volume Down
shift + XF86AudioLowerVolume
    pactl set-source-volume @DEFAULT_SOURCE@ -1%; \
    dunstify " Mic Volume Down:" -h int:value:$(pactl list sources | grep 'Volume:' | head -n 1 | awk -F / '{print $2}' | sed 's/ %//') -t 1000 -r 1

# Pipewire Controls Monitor Volume

# Monitor Volume Up
alt + XF86AudioRaiseVolume
    pactl set-source-volume @DEFAULT_SOURCE@ +1%; \
    dunstify "奔 Monitor Volume Up:" -h int:value:$(pactl list sources | grep 'Volume:' | head -n 1 | awk -F / '{print $2}' | sed 's/ %//') -t 1000 -r 1

# Monitor Volume Down
alt + XF86AudioLowerVolume
    pactl set-source-volume @DEFAULT_SOURCE@ -1%; \
    dunstify "奔 Monitor Volume Down:" -h int:value:$(pactl list sources | grep 'Volume:' | head -n 1 | awk -F / '{print $2}' | sed 's/ %//') -t 1000 -r 1

# Mute Speaker
XF86AudioMute
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    dunstify "婢 Mute/Unmute Speaker:" -h int:value:$(pactl list sinks | grep 'Mute:' | head -n 1 | awk '{print $2}') -t 1000 -r 1
