#!/bin/env bash

# BSPWM Config File
bspwmrc="${HOME}/.config/bspwm/bspwmrc"

# Rofi Command
rofi_command="rofi -modi drun -theme ${HOME}/.config/rofi/misc/misc.rasi -dmenu -selected-row 0 -p 'Switch the type of border' -show"

# Border Settings
border_1="bspc config border_width 5"
border_2="bspc config border_width 0"

# Variable passed to rofi
options="$border_1\n$border_2"

chosen="$(echo -e "$options" | $rofi_command)"
case "$chosen" in
    "$border_1")
        sed -i 's/bspc config border_width 0/bspc config border_width 5/g' "$bspwmrc"
        ;;
    "$border_2")
        sed -i 's/bspc config border_width 5/bspc config border_width 0/g' "$bspwmrc"
        ;;
    *)
        exit 1 # Handle unexpected input
        ;;
esac

# Reload BSPWM
bspc wm -r
