#!/bin/env bash

# Picom Config File
picom_conf="${HOME}/.config/picom/picom.conf"

# Rofi Command
rofi_command="rofi -modi drun -theme ${HOME}/.config/rofi/misc/misc.rasi -dmenu -selected-row 0 -p 'Switch the type of compositor' -show"

# Compositor Settings
compositor_1="corner-radius = 8"
compositor_2="corner-radius = 0"

# Variable passed to rofi
options="$compositor_1\n$compositor_2"

chosen="$(echo -e "$options" | $rofi_command)"
case "$chosen" in
    "$compositor_1")
        sed -i 's/corner-radius = 0/corner-radius = 8/g' "$picom_conf"
        ;;
    "$compositor_2")
        sed -i 's/corner-radius = 8/corner-radius = 0/g' "$picom_conf"
        ;;
    *)
        exit 1 # Handle unexpected input
        ;;
esac
