#!/bin/bash

# Rofi Command
rofi_command="rofi -modi drun -theme ${HOME}/.config/rofi/misc/powermenu.rasi -show"

# Options
options=("Logout" "Reboot" "Suspend" "Poweroff")

# Prompt
prompt="Select an option:"

# Get the user's choice using rofi
chosen=$(printf "%s\n" "${options[@]}" | $rofi_command -p "$prompt" -dmenu -selected-row 0)

# Perform actions based on the user's choice
case $chosen in
    "Logout")
        action="exit"
        message="Logout the system"
        ;;
    "Reboot")
        action="reboot"
        message="Reboot the system"
        ;;
    "Suspend")
        action="suspend"
        message="Suspend the system"
        ;;
    "Poweroff")
        action="poweroff"
        message="Power off the system"
        ;;
    *)
        exit 0
        ;;
esac

# Display a notification and perform the selected action
dunstify "$message"
sleep 2
loginctl $action
