#!/usr/bin/env bash

# Set the rofi theme
THEMER="$HOME/.config/rofi/misc/search.rasi"

# Define search engines and their URLs
declare -A URLS=(
  ["google"]="https://www.google.com/search?q="
  ["bing"]="https://www.bing.com/search?q="
  ["yahoo"]="https://search.yahoo.com/search?p="
  ["duckduckgo"]="https://www.duckduckgo.com/?q="
  ["yandex"]="https://yandex.ru/yandsearch?text="
  ["github"]="https://github.com/search?q="
  ["goodreads"]="https://www.goodreads.com/search?q="
  ["stackoverflow"]="http://stackoverflow.com/search?q="
  ["symbolhound"]="http://symbolhound.com/?q="
  ["searchcode"]="https://searchcode.com/?q="
  ["openhub"]="https://www.openhub.net/p?ref=homepage&query="
  ["superuser"]="http://superuser.com/search?q="
  ["askubuntu"]="http://askubuntu.com/search?q="
  ["imdb"]="http://www.imdb.com/find?ref_=nv_sr_fn&q="
  ["rottentomatoes"]="https://www.rottentomatoes.com/search/?search="
  ["piratebay"]="https://thepiratebay.org/search/"
  ["youtube"]="https://www.youtube.com/results?search_query="
  ["vimawesome"]="http://vimawesome.com/?q="
)

# Create a list of search engine names for rofi
gen_list() {
  for engine in "${!URLS[@]}"; do
    echo "$engine"
  done
}

# Main function for the script
main() {
  # Choose a search engine using rofi
  platform=$(gen_list | rofi -dmenu -modi drun -theme "$THEMER" -show -matching fuzzy -no-custom -p "Search > ")

  # Check if a search engine was selected
  if [[ -n "$platform" ]]; then
    # Input the search query
    query=$(rofi -dmenu -modi drun -theme "$THEMER" -show -matching fuzzy -p "Query > ")

    # Check if a query was provided
    if [[ -n "$query" ]]; then
      url="${URLS[$platform]}$query"
      xdg-open "$url"
    else
      exit
    fi
  else
    exit
  fi
}

main

exit 0
