#!/bin/bash

# Function to show an informational message
msg() {
    echo -e "\e[1;32m$*\e[0m"
}

# Function to generate an SSH key and add it to the agent
generate_and_add_ssh_key() {
    msg "Write Your Account here: Example 12345@gmail.com"
    read -e ACCOUNT
    ssh-keygen -t ed25519 -C "$ACCOUNT"
    msg "Connect To Agent"
    eval $(ssh-agent -s)
    ssh-add
}

# Function to display the SSH key
show_ssh_key() {
    msg "Grep Your Ssh"
    cat ~/.ssh/id_ed25519.pub
}

# Function to test the SSH connection to GitHub
test_ssh_connection() {
    msg "Testing Connect Ssh Github"
    ssh -T git@github.com
    msg "Yeayy Your Ssh Working Properly Now"
}

# Main function to run all steps
main() {
    generate_and_add_ssh_key
    show_ssh_key
    test_ssh_connection
}

main
