#!/bin/bash

# Rofi Command
rofi_command="rofi -lines 2 -theme ${HOME}/.config/rofi/misc/misc.rasi"

# Common function to update themes
update_theme() {
    sed -i -e "s/$1/$2/g" ${HOME}/.xsettingsd
    sed -i -e "s/$1/$2/g" ${HOME}/.config/rofi/clean.rasi
    sed -i -e "s/$1/$2/g" ${HOME}/.config/rofi/config.rasi
    sed -i -e "s/$1/$2/g" ${HOME}/.config/kitty/kitty.conf
    sed -i -e "s/$1/$2/g" ${HOME}/.config/gtk-3.0/settings.ini
    sed -i -e "s/$1/$2/g" ${HOME}/.config/rofi/misc/misc.rasi
    sed -i -e "s/$1/$2/g" ${HOME}/.config/rofi/misc/search.rasi
    sed -i -e "s/$1/$2/g" ${HOME}/.config/rofi/misc/network.rasi
    sed -i -e "s/$1/$2/g" ${HOME}/.config/rofi/misc/powermenu.rasi
    sed -i -e "s/$1/$2/g" ${HOME}/.config/rofi/misc/screenshot.rasi
    sed -i -e "s/background = \"$3\"/background = \"$4\"/g" ${HOME}/.config/dunst/dunstrc
    sed -i -e "s/foreground = \"$4\"/foreground = \"$3\"/g" ${HOME}/.config/dunst/dunstrc
    sed -i -e "s/$1/$2/g" ${HOME}/.config/bspwm/bspwmrc
    sed -i -e "s/$5/$6/g" ${HOME}/.fehbg
}

# Kill Processes
kill_processes() {
    kill kitty sxhkd dunst tint2
    kill $USR1 kitty
    bspc wm -r
}

# Themes
theme_0="dark"
theme_1="light"
background_dark="#030303"
background_light="#FAFAFA"

# Variable passed to rofi
options="$theme_0\n$theme_1"

chosen="$(echo -e "$options" | $rofi_command -p "themes" -show -dmenu -sync -selected-row 0)"

case $chosen in
    $theme_0)
        update_theme "light" "dark" "$background_light" "$background_dark" "mountain.jpg" "tree.jpg"
        kill_processes
        ;;
    $theme_1)
        update_theme "dark" "light" "$background_dark" "$background_light" "tree.jpg" "mountain.jpg"
        kill_processes
        ;;
esac
